######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 2 21:47:34 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += hellodialog.ui
SOURCES += main.cpp
