######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 2 21:19:51 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
